server:
  port: 8082

spring:
  application:
    name: player-profile

  datasource:
    url: jdbc:postgresql://localhost:5433/${POSTGRES_DB:ovr_db}
    username: ${POSTGRES_USER:ovr_user}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: player-profile-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: lol.ovr.player_profile.infrastructure.adapter.in.kafka.KafkaOvrCardConsumer$OvrCardEventPayload

ovr:
  kafka:
    topic:
      card-generated: ovr.card.generated.v1